import oracledb

# Connect to the Oracle Database
connection =  oracledb.makedsn("db-etu.univ-lyon2.fr","1521","DBETU")

con = oracledb.connect(user="m125",password="m125",dsn=connection)

cursor = con.cursor()

table_name = "'STRUCTURE','HOSTELREVIEW','SITEREVIEW'"
table_check_query = f"SELECT table_name FROM all_tables WHERE table_name IN ({table_name})"
cursor.execute(table_check_query)

tables = [table[0] for table in cursor.fetchall()]


if 'STRUCTURE' in tables:
  print("structure already exists")
else:
  table = ('''CREATE TABLE STRUCTURE (
      ID int primary key NOT NULL,
      type varchar(255),
      name varchar(255))''')
  cursor.execute(table)
  print('Table created: STRUCTURE')


if 'HOSTELREVIEW' in tables:
  print("hostelreview already exists")
else:
  table = ('''CREATE TABLE hostelreview (
      ReviewID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
      Name varchar(255),
      ReviewRate int,
      ReviewTime varchar(255),
      RewiewVisite varchar(255),
      ReviewText CLOB ,
      VoyageType varchar(255),
      RoomRate NUMBER(2,1),
      EmplacementRate NUMBER(2,1),
      ServiceRate NUMBER(2,1),
      HostelType int,
      FOREIGN KEY (HostelType) REFERENCES structure(ID)
  )''')
  cursor.execute(table)
  print('Table created: HOSTELREVIEW')


if 'SITEREVIEW' in tables:
  print("sitereview already exists")
else:
  table = ('''CREATE TABLE sitereview (
      ReviewID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
      Name varchar(255),
      ReviewRate int,
      ReviewTime varchar(255),
      RewiewVisite varchar(255),
      ReviewText VARCHAR2(4000),
      SiteType int,
      FOREIGN KEY (SiteType) REFERENCES structure(ID)
  )''')
  cursor.execute(table)
  print('Table created: SITEREVIEW')